version: "3.2"
services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
     - "6379:6379"
  mongodb_container:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"

  taoscan_client:
    image: "taoscan_client:latest"
    container_name: "taoscan_client"
    ports:
      - "3000:3000"
    restart: unless-stopped
  taoscan_server:
    image: "taoscan_server:latest"
    container_name: "taoscan_server"
    expose:
      - 3333
    command: start
    restart: unless-stopped
  taoscan_server2:
    image: "taoscan_server:latest"
    container_name: "taoscan_server_producer"
    command: run producer
    restart: unless-stopped
  taoscan_server3:
    image: "taoscan_server:latest"
    container_name: "taoscan_server_txsubscribe"
    command: run subscribe
    restart: unless-stopped
  taoscan_server4:
    image: "taoscan_server:latest"
    container_name: "taoscan_server_crawl"
    command: run crawl
    restart: unless-stopped
